import type { Report } from '../../types/report.types'

const now = new Date().toISOString()

import COMM_A_PHOTO_BLOWER_HOUSE from './assets/comm-a-blower-house.jpg?inline'
import COMM_A_PHOTO_HEADER_PIPING from './assets/comm-a-header-piping.jpg?inline'
import COMM_A_PHOTO_AERATION_TANKS from './assets/comm-a-aeration-tanks.jpg?inline'

export const sampleReports: Report[] = [
  {
    id: 'report-meadville-1',
    clientId: 'client-invent-pacific',
    clientName: 'INVENT PACIFIC',
    projectName: 'Meadville 1',
    operatorName: 'Technician MVP',
    reportDate: now.slice(0, 10),
    language: 'en',
    templateId: 'iturbo-blower-service',
    status: 'final',
    syncStatus: 'synced',
    unitSystem: 'metric',
    generalComments: 'Reference sample report with multiple blower units and technical readings.',
    signatureDataUrl: '',
    customFields: [
      { key: 'Site', value: 'Meadville' },
      { key: 'Client Ref', value: 'MEAD-001' },
    ],
    equipmentUnits: [
      {
        id: 'unit-a',
        name: 'Blower A',
        model: 'iTB150-10',
        serialNumber: 'ITB-A-001',
        nominalVoltage: 460,
        notes: 'Rear bearing vibration noted, monitor during next maintenance cycle.',
        photoUrls: [
          'https://picsum.photos/seed/meadville-a-1/800/600',
          'https://picsum.photos/seed/meadville-a-2/800/600',
        ],
        checklistItems: [
          {
            id: 'a-1',
            category: 'electrical',
            itemLabel: 'Verify incoming voltage',
            status: 'pass',
            selectedCommonDefect: '',
            comment: '',
          },
          {
            id: 'a-2',
            category: 'safety',
            itemLabel: 'Verify safety guards',
            status: 'fail',
            selectedCommonDefect: 'Guard missing',
            comment: 'Guard missing near service side panel.',
          },
        ],
        technicalReadings: [
          {
            id: 'a-r1',
            pointLabel: 'Loaded Point 1',
            rpm: 4750,
            current: 18.2,
            power: 12.4,
            flow: 36.5,
            pressure: 52.2,
            voltageMeasured: 476.5,
            voltageToleranceStatus: 'ok',
            speedPercent: 80,
          },
        ],
      },
      {
        id: 'unit-b',
        name: 'Blower B',
        model: 'iTB150-10',
        serialNumber: 'ITB-B-002',
        nominalVoltage: 460,
        notes: 'Unit cleaned and visually confirmed in acceptable operating condition.',
        photoUrls: ['https://picsum.photos/seed/meadville-b-1/800/600'],
        checklistItems: [
          {
            id: 'b-1',
            category: 'mechanical',
            itemLabel: 'Inspect blower alignment',
            status: 'pass',
            selectedCommonDefect: '',
            comment: '',
          },
          {
            id: 'b-2',
            category: 'hydraulic',
            itemLabel: 'Check lubrication system',
            status: 'pass',
            selectedCommonDefect: '',
            comment: '',
          },
        ],
        technicalReadings: [
          {
            id: 'b-r1',
            pointLabel: 'Loaded Point 1',
            rpm: 4680,
            current: 17.6,
            power: 11.9,
            flow: 35.1,
            pressure: 50.7,
            voltageMeasured: 475,
            voltageToleranceStatus: 'ok',
            speedPercent: 78,
          },
        ],
      },
    ],
    attachments: [],
    commissioning: {
      customerInformation: {
        plantName: 'Meadville WWTP',
        plantAddress: 'Meadville, PA, USA',
        primaryContactName: 'Technical Service',
        primaryContactEmail: 'service@inventpacific.example',
      },
      applicationProcessInfo: {
        numberOfBlowers: '2 (sample)',
        blowerModel: 'iTB150-10',
        blowerSNs: 'ITB-A-001, ITB-B-002',
        aerationProcess: 'Commissioning sample',
        waterDepth: '—',
        aerationDevice: '—',
      },
      inputVoltageRecordings: {
        rEarth: 275.5,
        wEarth: 277.1,
        bEarth: 277.2,
        rW: 475,
        rB: 476.5,
        wB: 478.9,
      },
      inputPowerRecordings: {
        rBVoltage: 478,
        rWVoltage: 479,
        bWVoltage: 481,
        rRmsCurrent: 27.6,
        wRmsCurrent: 29.5,
        bRmsCurrent: 32.8,
      },
      loadedOperation: [
        {
          id: 'loaded-39',
          svPercent: 39,
          motorRpm: 25000,
          currentRwb: 71,
          powerKw: 38.7,
          flowM3Min: 36.9,
          p2Kpa: 56.5,
          deltaPPa: 48,
          t1C: 23.4,
          t2C: 58.8,
        },
        {
          id: 'loaded-83',
          svPercent: 83,
          motorRpm: 30800,
          currentRwb: 146.5,
          powerKw: 103.8,
          flowM3Min: 83.1,
          p2Kpa: 58.6,
          deltaPPa: 143,
          t1C: 23.5,
          t2C: 90,
        },
      ],
      scadaControlChecks: [
        { id: 'scada-1', label: 'SV Signal to Blower (check with change)', value: 'yes', comment: '' },
        { id: 'scada-2', label: 'Error Codes to Customer SCADA', value: 'yes', comment: 'Digital Fault / Alarm' },
        { id: 'scada-3', label: 'Monitoring Data to Customer SCADA', value: 'yes', comment: '' },
      ],
      results: {
        minSv: '39 m³/min (1306 SCFM)',
        maxSv: '83 m³/min (2931 SCFM)',
        minOperatingPressure: '56.4 kPa',
        maxOperatingPressure: '58.6 kPa',
        airFlowRange: 'As min-max SV',
      },
      signatures: {
        technicianName: 'Technician MVP',
        customerName: 'Customer',
        technicianSignedAt: now.slice(0, 10),
        customerSignedAt: '',
      },
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'report-commissioning-a',
    clientId: 'client-commissioning-demo',
    clientName: 'COMMISSIONING DEMO CLIENT',
    projectName: 'Commissioning Report A',
    operatorName: 'Technician MVP',
    reportDate: now.slice(0, 10),
    language: 'en',
    templateId: 'iturbo-blower-service',
    status: 'final',
    syncStatus: 'synced',
    unitSystem: 'metric',
    generalComments:
      'Sample commissioning report (Report A) filled as if entered by the user. Includes commissioning tables for voltage, power, loaded operation, SCADA checks, and results.',
    signatureDataUrl: '',
    customFields: [
      { key: 'Site', value: 'Demo WWTP' },
      { key: 'Client Ref', value: 'COMM-A-001' },
    ],
    equipmentUnits: [
      {
        id: 'unit-1',
        name: 'Blower 1',
        model: 'iTB250-12',
        serialNumber: 'ITB-250-12-A001',
        nominalVoltage: 460,
        notes: 'Commissioning baseline point captured at multiple SV%.',
        photoUrls: ['https://picsum.photos/seed/commissioning-a-unit-1/800/600'],
        checklistItems: [
          {
            id: 'c-1',
            category: 'electrical',
            itemLabel: 'Verify incoming voltage',
            status: 'pass',
            selectedCommonDefect: '',
            comment: '',
          },
          {
            id: 'c-2',
            category: 'safety',
            itemLabel: 'Verify safety guards',
            status: 'pass',
            selectedCommonDefect: '',
            comment: '',
          },
        ],
        technicalReadings: [
          {
            id: 'c-r1',
            pointLabel: 'Loaded Point',
            rpm: 29000,
            current: 96.4,
            power: 62.3,
            flow: 58.2,
            pressure: 57.1,
            voltageMeasured: 478.2,
            voltageToleranceStatus: 'ok',
            speedPercent: 60,
          },
        ],
      },
    ],
    attachments: [],
    commissioning: {
      customerInformation: {
        plantOwner: 'Municipal Utility (Demo)',
        plantName: 'Demo WWTP',
        plantAddress: 'Querétaro, MX',
        primaryContactName: 'Operations Manager',
        primaryContactEmail: 'ops@demo-client.example',
      },
      applicationProcessInfo: {
        numberOfBlowers: '1',
        blowerModel: 'iTB250-12',
        blowerSNs: 'ITB-250-12-A001',
        aerationProcess: 'Aeration Basin (Demo)',
        waterDepth: '4.5 m',
        aerationDevice: 'Fine bubble diffusers',
      },
      photos: {
        blowerHouse: [COMM_A_PHOTO_BLOWER_HOUSE],
        headerPiping: [COMM_A_PHOTO_HEADER_PIPING],
        aerationTanksValves: [COMM_A_PHOTO_AERATION_TANKS],
      },
      inputVoltageRecordings: {
        rEarth: 276.8,
        wEarth: 277.4,
        bEarth: 276.9,
        rW: 478.1,
        rB: 477.6,
        wB: 478.9,
      },
      inputPowerRecordings: {
        rBVoltage: 478,
        rWVoltage: 479,
        bWVoltage: 480,
        rRmsCurrent: 45.2,
        wRmsCurrent: 47.8,
        bRmsCurrent: 49.1,
      },
      loadedOperation: [
        {
          id: 'loaded-40',
          svPercent: 40,
          motorRpm: 25000,
          currentRwb: 62.1,
          powerKw: 34.8,
          flowM3Min: 38.5,
          p2Kpa: 55.8,
          deltaPPa: 55,
          t1C: 24.0,
          t2C: 61.2,
        },
        {
          id: 'loaded-60',
          svPercent: 60,
          motorRpm: 29000,
          currentRwb: 96.4,
          powerKw: 62.3,
          flowM3Min: 58.2,
          p2Kpa: 57.1,
          deltaPPa: 96,
          t1C: 24.2,
          t2C: 78.5,
        },
        {
          id: 'loaded-80',
          svPercent: 80,
          motorRpm: 32000,
          currentRwb: 136.7,
          powerKw: 98.4,
          flowM3Min: 78.9,
          p2Kpa: 58.4,
          deltaPPa: 142,
          t1C: 24.4,
          t2C: 92.0,
        },
      ],
      scadaControlChecks: [
        { id: 'scada-a-1', label: 'SV Signal to Blower (check with change)', value: 'yes', comment: '' },
        { id: 'scada-a-2', label: 'Error Codes to Customer SCADA', value: 'yes', comment: 'Fault relay verified' },
        { id: 'scada-a-3', label: 'Monitoring Data to Customer SCADA', value: 'yes', comment: 'RPM / kW / Pressure visible' },
      ],
      results: {
        minSv: '40 m³/min',
        maxSv: '80 m³/min',
        minOperatingPressure: '55.8 kPa',
        maxOperatingPressure: '58.4 kPa',
        airFlowRange: 'As min-max SV',
      },
      signatures: {
        technicianName: 'Technician MVP',
        customerName: 'Operations Manager',
        technicianSignedAt: now.slice(0, 10),
        customerSignedAt: '',
      },
    },
    createdAt: now,
    updatedAt: now,
  },
]

